[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_cpi = "BbBXo1vyGPcUvZP2KasdJ7peobAU4zq5snUAxZYmQyS"

[programs.devnet]
solana_cpi = "BbBXo1vyGPcUvZP2KasdJ7peobAU4zq5snUAxZYmQyS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
